### ISSUE TITLE
Refactor custom actions to accept arguments and behave more like functions

### ISSUE THREAD

**Issue by electrikmilk** [electrikmilk/cherri#19]
The implementation of a simple addition "function" in Shortcuts in Cherri looks like this:

```ruby
if ShortcutInput {
    const inputType = typeOf(ShortcutInput)
    if inputType == "Dictionary" {
        const input = getDictionary(ShortcutInput)
        const identifier = getValue(input, "cherri_functions")
        const valid = number(identifier)
        if valid == true {
            const function_name = getValue(input, "function")
            const function = "{function_name}"
            const args = getValue(input, "arguments")
            if function == "add" {
                const arg1 = getListItem(args, 0)
                const arg2 = getListItem(args, 1)
                const n1 = number(arg1)
                const n2 = number(arg2)
                const result = n1 + n2
                output("{result}")
            }
        }
    }
}

const operandOne = prompt("Operand 1", "Number", "2")
const operandTwo = prompt("Operand 2", "Number", "2")

const myFunctionCall = {
    "cherri_functions": 1,
    "function": "add",
    "arguments": ["{operandOne}", "{operandTwo}"]
}
const myFunctionReturn = runSelf(myFunctionCall)

alert(myFunctionReturn)

```

This has recently become possible through some focused work on this implementation and is tested to work.

This would allow custom actions to have their own scope.

We would want the definition for this to look like this:

```ruby
action add(number n1, number n2) {
    const result = n1 + n2
    output("{result}")
}

add(2, 2)
```

So this will need to be generated based on custom action definitions and references.

**Comment by erenyenigul** [comment]
Hey @electrikmilk, I want to contribute to the project. I am trying to find your contact information for my detailed questions. Can you add your email or another information for me to reach you?

**Comment by electrikmilk** [comment]
> Hey @electrikmilk, I want to contribute to the project. I am trying to find your contact information for my detailed questions. Can you add your email or another information for me to reach you?

Thank you for your interest in the project! I will send you an email from my personal email to the email listed on your site.

**Comment by electrikmilk** [comment]
> Came here to suggest “functions” but glad to see you’re already on it! Just finding out about this project via the [RoutineHub blog post](https://blog.routinehub.co/introducing-cherri-a-development-environment-for-apple-shortcuts/). Amazing work!

Thanks so much for your interest in the project! I'm really glad to see people are excited about this upcoming feature.

**Comment by twilsonco** [comment]
The alternative is, for more complicated shortcuts like this [Photo collage](https://routinehub.co/shortcut/17870/) tool I recently made, to develop "functions" as separate shortcuts and then use something like Join shortcuts to put everything together, but it requires so much more work. Something like what you're doing (also what [JellyCuts](https://apps.apple.com/us/app/jellycuts/id1522625245) does, though it's very buggy) makes it feel 1000X more approachable. 

Also, the structure of your project makes me really want to get involved, so that I can PR all my selfish wish-list actions and features! Kudos again.

**Comment by twilsonco** [comment]
Sidenote: is there a way I can support your work?

**Comment by electrikmilk** [comment]
> The alternative is, for more complicated shortcuts like this [Photo collage](https://routinehub.co/shortcut/17870/) tool I recently made, to develop "functions" as separate shortcuts and then use something like Join shortcuts to put everything together, but it requires so much more work. Something like what you're doing (also what [JellyCuts](https://apps.apple.com/us/app/jellycuts/id1522625245) does, though it's very buggy) makes it feel 1000X more approachable. 
> 
> 
> 
> Also, the structure of your project makes me really want to get involved, so that I can PR all my selfish wish-list actions and features! Kudos again.

That's great to hear! Haha, yes, please do report an issues you run into while making your Shortcuts :)

**Comment by electrikmilk** [comment]
> Sidenote: is there a way I can support your work?

Hmm, perhaps I will need to look into setting up a Github sponsors 🤔

**Comment by electrikmilk** [comment]
I'd like to do a bit more testing before merging into main, but this work is finally done.

I started fresh recently due to external changes made since I worked on the old branch.

I also had to fix an issue with action constants first.

This new implementation collects action definitions in a pre-parsing loop like the original branch implementation.

However, instead of replacing references to those defined actions, during the main parsing loop when we collect standard actions, if it's a custom action, we just create different tokens of a Dictionary and Run Shortcut actions like in the code above.

**Comment by electrikmilk** [comment]
> However, instead of replacing references to those defined actions, during the main parsing loop when we collect standard actions, if it's a custom action, we just create different tokens of a Dictionary and Run Shortcut actions like in the code above.

We do this so that we don't have to separately keep track of variable references, users should be able to enter arguments to a custom action reference just like they normally would. This also doesn't change the contents of the file save for the generated header where all of the definitions live.

**Comment by electrikmilk** [comment]
I've decided macros will be a separate issue, but shouldn't take too long.

I also want to make that distinct from custom actions so it's understood what the difference is.
