### ISSUE TITLE
Using the `takePhotos(count)` function causes an error during parsing

### ISSUE THREAD

**Issue by mikeogezi** [electrikmilk/cherri#26]
**Describe the bug**
The `takePhotos(count)` function causes the parser to panic

**To Reproduce**
```ruby
takePhotos(2)
```

**Debug output**
```
Parsing main.cherri...
panic: interface conversion: interface {} is string, not int

goroutine 1 [running]:
main.mediaActions.func1({0x14000076220?, 0x1400007a4e0?, 0x140000101e0?})
        /Users/michaelogezi/go/pkg/mod/github.com/mikeogezi/cherri@v0.0.0-20231031104858-73b6edfe5d87/actions_std.go:1746 +0xa0
main.checkAction()
        /Users/michaelogezi/go/pkg/mod/github.com/mikeogezi/cherri@v0.0.0-20231031104858-73b6edfe5d87/action.go:206 +0xb4
main.collectAction()
        /Users/michaelogezi/go/pkg/mod/github.com/mikeogezi/cherri@v0.0.0-20231031104858-73b6edfe5d87/parser.go:1154 +0x1cc
main.collectActionCall()
        /Users/michaelogezi/go/pkg/mod/github.com/mikeogezi/cherri@v0.0.0-20231031104858-73b6edfe5d87/parser.go:1130 +0x24
main.parse()
        /Users/michaelogezi/go/pkg/mod/github.com/mikeogezi/cherri@v0.0.0-20231031104858-73b6edfe5d87/parser.go:179 +0x2cc
main.initParse()
        /Users/michaelogezi/go/pkg/mod/github.com/mikeogezi/cherri@v0.0.0-20231031104858-73b6edfe5d87/parser.go:49 +0x31c
main.main()
        /Users/michaelogezi/go/pkg/mod/github.com/mikeogezi/cherri@v0.0.0-20231031104858-73b6edfe5d87/main.go:62 +0x258
```

**Expected behavior**
I expect this to compile into a valid Shortcut.

**Screenshots**
N/A

**Version Information (please complete the following information):**
 - macOS version: Darwin Michaels-MacBook-Air.local 23.2.0 Darwin Kernel Version 23.2.0: Fri Oct 13 09:28:08 PDT 2023; root:xnu-10002.60.54~14/RELEASE_ARM64_T8112 arm64
 - Golang version: go version go1.21.3 darwin/arm64

**Additional context**
N/A

**Comment by electrikmilk** [comment]
Closed by [2614b66](https://github.com/electrikmilk/cherri/commit/2614b664916b8e2ee36f345cd7efd027ebb04e28).

This merges the takePhoto() and takePhotos() actions and combines the number of photos and preview arguments by proxy. It no longer casts the argument to an int and just makes sure it's not "0".
