### ISSUE TITLE
The `getCurrentWeather()` function produces an invalid Shortcut 

### ISSUE THREAD

**Issue by mikeogezi** [electrikmilk/cherri#27]
**Describe the bug**
The `getCurrentWeather()` function produces a Shortcut with an invalid action. The action seems to be incompatible with the current version of Shortcuts.

**To Reproduce**
```ruby
getCurrentWeather()
```

**Debug output**
N/A

**Expected behavior**
I expect the action produced in the Shortcut to be valid.

**Screenshots**
- macOS (Sonoma 14.2)
  <img width="428" alt="Screenshot 2023-11-02 at 3 06 07 AM" src="https://github.com/electrikmilk/cherri/assets/10839579/ac78adca-e872-47b6-aa62-19b2409b38db">
- iOS (17.1)
  ![IMG_010FF01037D3-1](https://github.com/electrikmilk/cherri/assets/10839579/66675910-b9cf-4b49-81c2-6e1f1958bd69)

**Version Information (please complete the following information):**
- macOS version: Darwin Michaels-MacBook-Air.local 23.2.0 Darwin Kernel Version 23.2.0: Fri Oct 13 09:28:08 PDT 2023; root:xnu-10002.60.54~14/RELEASE_ARM64_T8112 arm64
- Golang version: go version go1.21.3 darwin/arm64

**Additional context**
N/A

**Comment by electrikmilk** [comment]
Closed by [e8aa2e7](https://github.com/electrikmilk/cherri/commit/e8aa2e7d8533c9b17a5468bf24a9f6ca6c0990e5).
