### ISSUE TITLE
Unable to limit the number of contacts with `filterContacts`

### ISSUE THREAD

**Issue by mikeogezi** [electrikmilk/cherri#29]
**Describe the bug**
When the limit argument of `filterContacts(variable contacts, enum ?sortByProperty, enum ?sortOrder = "A to Z", integer ?limit)` is set, the produced Shortcut is still unable to limit the contacts because a boolean that enables limiting is not set.

**To Reproduce**
```ruby
filterContacts(nil, "First Name", "A to Z", 6)
```

**Debug output**
N/A

**Expected behavior**
When a limit is set, the limit should be enabled implicitly

**Screenshots**
- What is produced: 
  <img width="643" alt="Screenshot 2023-11-02 at 6 06 07 PM" src="https://github.com/electrikmilk/cherri/assets/10839579/8a2050d2-a520-4ecb-8e37-bffdcdfc8a25">
- What is expected: 
  <img width="640" alt="Screenshot 2023-11-02 at 6 06 17 PM" src="https://github.com/electrikmilk/cherri/assets/10839579/e9089c79-92b7-4dc7-9b06-346bbd331207">

**Version Information (please complete the following information):**
 - macOS version (run `uname -a`): Darwin Michaels-MacBook-Air.local 23.2.0 Darwin Kernel Version 23.2.0: Fri Oct 13 09:28:08 PDT 2023; root:xnu-10002.60.54~14/RELEASE_ARM64_T8112 arm64
 - Golang version (run `go version`): go version go1.21.3 darwin/arm64

**Additional context**
N/A

**Comment by mikeogezi** [comment]
@electrikmilk Proposed fix: https://github.com/electrikmilk/cherri/pull/28/

**Comment by electrikmilk** [comment]
Closed by https://github.com/electrikmilk/cherri/pull/28.
