### ISSUE TITLE
Mac Signing Server

### ISSUE THREAD

**Issue by electrikmilk** [electrikmilk/cherri#3]
Currently, there is a way to try-out Cherri on any platform at [playground.cherrilang.org](https://playground.cherrilang.org/). However, it does not have a Mac signing server yet. I am hoping to eventually host a Mac signing server.

### Plan A: MacStadium Open Source Program

Apply to the Open Source program from [MacStadium](https://www.macstadium.com/), which offers [free Mac hosting for open-source projects](https://www.macstadium.com/opensource), but [there are some catches](https://www.macstadium.com/opensource#so:~:text=So%20what%E2%80%99s%20the%20catch%3F), meaning this project will probably need to mature more before that could happen.

### Plan B: Dedicated Hosting

Pay for **expensive** Mac hosting (expensive for hosting) from the small number of Mac hosting options.

**This is probably not going to happen.** The reason it's so expensive is that you can't use a VPS server for signing Shortcuts––I have tried. Shortcut signing requires an iCloud sign-in which (unless you wanna jump through a bunch of hoops) requires a legit Mac, so we would need to pay for a dedicated Mac server, which is expensive in the first place for a Linux server, but even more so for a Mac (around $70-100/mo at least).

---

<s>[Darling](https://github.com/darlinghq/darling)?</s> I tried it, but it currently does not have the ContentKit private framework, and would probably not work for signing shortcuts as iCloud sign-in is needed.

The web editor / playground is the right way to get non-technical people interested in using the language in my opinion over an app, as anyone with a web browser can use it.

I really like what the [ScPL editor](https://editor.scpl.dev) did, so much so that I had some minor involvement in it. However, it doesn’t support Shortcuts past iOS 13.

**Comment by electrikmilk** [comment]
Investigating this possibility: https://github.com/sickcodes/Docker-OSX

**Comment by scaxyz** [comment]
Here is a simple server for signing shortcuts via http and a guide on running it via docker-osx, maybe you find it useful.
https://github.com/scaxyz/shortcut-signing-server

**Comment by electrikmilk** [comment]
> Here is a simple server for signing shortcuts via http and a guide on running it via docker-osx, maybe you find it useful.
> 
> https://github.com/scaxyz/shortcut-signing-server

This is awesome, I will definitely give this a shot!

**Comment by electrikmilk** [comment]
This has been solved in collaboration with the RoutineHub team! Huge thanks to them for setting up a server we could use to do this in the playground. ❤️

Try it out at https://playground.cherrilang.org/
