### ISSUE TITLE
Issue with retrieving unitType enums from a list

### ISSUE THREAD

**Issue by mikeogezi** [electrikmilk/cherri#32]
**Describe the bug**
I run into a panic when I try to use a unitType enum that I retrieved from a list as an argument. This is similar to Issue https://github.com/electrikmilk/cherri/issues/31

**To Reproduce**
```ruby
@utlist = list("Length", "Angle")
@l = getListItem(utlist, 0)
@a = getListItem(utlist, 1)
@meas = measurement("2000", l, "meter")
@val = convertMeasurement(meas, l, "ft")
```

**Debug output**
Parsing custom actions... ### CUSTOM ACTIONS ###

done!
Parsing test.cherri...
panic: interface conversion: interface {} is main.action, not string

goroutine 1 [running]:
main.webActions.func11({0x14000104300, 0x3, 0x140000ae910?})
        /Users/michaelogezi/Documents/projects/-cherri/cherri/actions_std.go:4926 +0x158
main.checkAction()
        /Users/michaelogezi/Documents/projects/-cherri/cherri/action.go:204 +0x7c
main.collectAction()
        /Users/michaelogezi/Documents/projects/-cherri/cherri/parser.go:1195 +0x270
main.collectValue(0x14000111790, 0x140001117a0, 0xa)
        /Users/michaelogezi/Documents/projects/-cherri/cherri/parser.go:308 +0x4e4
main.collectVariableValue(0x0, 0x14000111790, 0x140001117a0, 0x140001117d0, 0x140001117c0)
        /Users/michaelogezi/Documents/projects/-cherri/cherri/parser.go:241 +0x3c
main.collectVariable(0x0)
        /Users/michaelogezi/Documents/projects/-cherri/cherri/parser.go:486 +0x6e8
main.parse()
        /Users/michaelogezi/Documents/projects/-cherri/cherri/parser.go:148 +0x480
main.initParse()
        /Users/michaelogezi/Documents/projects/-cherri/cherri/parser.go:50 +0x2f4
main.main()
        /Users/michaelogezi/Documents/projects/-cherri/cherri/main.go:75 +0x35c
exit status 2

**Expected behavior**
I expect the retrieved enum to work as an argument.

**Screenshots**
N/A

**Version Information (please complete the following information):**
 - macOS version (run `uname -a`): Darwin Michaels-MacBook-Air.local 23.2.0 Darwin Kernel Version 23.2.0: Fri Oct 13 09:28:08 PDT 2023; root:xnu-10002.60.54~14/RELEASE_ARM64_T8112 arm64
 - Golang version (run `go version`): go version go1.21.4 darwin/arm64

**Additional context**
N/A

**Comment by electrikmilk** [comment]
Thanks for finding this! We have more a complex value structure for measurements that require manual enum checking.

Part of this is not possible to fix, as the measurement action does not accept variables in the Shortcuts app itself.
