### ISSUE TITLE
Add to/Subtract from date not producing a valid Shortcut when the magnitude is a variable

### ISSUE THREAD

**Issue by mikeogezi** [electrikmilk/cherri#35]
**Describe the bug**
Add to date: 
```
addSeconds(string date, integer magnitude)
addMinutes(string date, integer magnitude)
addHours(string date, integer magnitude)
addDays(string date, integer magnitude)
addWeeks(string date, integer magnitude)
addMonths(string date, integer magnitude)
addYears(string date, integer magnitude)
``` 
&

Subtract from date:
```
subtractSeconds(string date, integer magnitude)
subtractMinutes(string date, integer magnitude)
subtractHours(string date, integer magnitude)
subtractDays(string date, integer magnitude)
subtractWeeks(string date, integer magnitude)
subtractMonths(string date, integer magnitude)
subtractYears(string date, integer magnitude)
```
 
do not produce valid shortcuts when the magnitude is a variable.

**To Reproduce**
```ruby
@d = date("October 5, 2022")
@a = 2
addDays(d, a)
```

**Debug output**
_The compilation is successful, but below is a screenshot of the Shortcut._

<img width="640" alt="Screenshot 2023-12-05 at 6 41 27 PM" src="https://github.com/electrikmilk/cherri/assets/10839579/0b5b6a1b-b98a-4a02-85a8-03436cd96f28">

**Expected behavior**

<img width="629" alt="Screenshot 2023-12-05 at 6 43 15 PM" src="https://github.com/electrikmilk/cherri/assets/10839579/12f7f166-9d5d-4de1-b724-a5d4c9ff09bf">

**Screenshots**
_See above._

**Version Information (please complete the following information):**
 - macOS version (run `uname -a`): Darwin Michaels-MacBook-Air.local 23.2.0 Darwin Kernel Version 23.2.0: Fri Oct 13 09:28:08 PDT 2023; root:xnu-10002.60.54~14/RELEASE_ARM64_T8112 arm64
 - Golang version (run `go version`): go version go1.21.4 darwin/arm64

**Additional context**
N/A

**Comment by electrikmilk** [comment]
> @electrikmilk, if you could give me a few pointers for some of these past issues, I might be able to help.

Sure, I will do my best. A lot of these issues boil down to variations in data structure for these different actions. They require a custom structure for the value of one of their parameters. Thus they require adding a custom solution to fit their data structure and insert a variable or an inline variable value into their parameters within a make function defined on the action definition.

For example with this issue, these date actions have their make function called `adjustDate()` which creates them based on the structure for this type of action. In this case, this has a custom structure for the magnitude value that has a custom serialization type to specify (which most action parameters do not need to specify) and a unit value that needs to be in the same data as the magnitude value, this is not standard for the rest of the actions in the compiler.

For more insight on this fix, check out [0675510](https://github.com/electrikmilk/cherri/commit/0675510943e014e025a38f2b344f543d901f9b11), which fixes this issue.
