### ISSUE TITLE
Variable arguments to `killAllApps`, `hideAllApps`, and `quitAllApps` are treated as constants

### ISSUE THREAD

**Issue by mikeogezi** [electrikmilk/cherri#38]
**Describe the bug**
The _app id_ that I set the variable to is used as the argument to the action (`killAllApps`, `hideAllApps`, or `quitAllApps`) instead of the _variable_.

**To Reproduce**
```ruby
@e = "com.apple.mobilesafari"
killAllApps(e)
```
```ruby
@e = "com.apple.mobilesafari"
hideAllApps(e)
```
```ruby
@e = "com.apple.mobilesafari"
quitAllApps(e)
```

**Debug output**
_There is no compile error, but this a screenshot of the problematic Shortcut_

<img width="642" alt="Screenshot 2023-12-05 at 8 24 23 PM" src="https://github.com/electrikmilk/cherri/assets/10839579/cc94d6db-83b9-4d03-a1d6-e53250346dca">

**Expected behavior**

<img width="643" alt="Screenshot 2023-12-05 at 8 24 45 PM" src="https://github.com/electrikmilk/cherri/assets/10839579/59e01f3c-1f14-4fc3-893d-57a89cc203da">

**Version Information (please complete the following information):**
 - macOS version (run `uname -a`): Darwin Michaels-MacBook-Air.local 23.2.0 Darwin Kernel Version 23.2.0: Fri Oct 13 09:28:08 PDT 2023; root:xnu-10002.60.54~14/RELEASE_ARM64_T8112 arm64
 - Golang version (run `go version`): go version go1.21.4 darwin/arm64

**Comment by electrikmilk** [comment]
We were not properly handling variables and were just expecting string values. This is fixed by [13c1147](https://github.com/electrikmilk/cherri/commit/13c1147492dfba23d3c25db10a1866580e4c9f03).
