### ISSUE TITLE
Setting a variable to the result of an action produces self-referential Set Variable actions that don't work

### ISSUE THREAD

**Issue by NoelTautges** [electrikmilk/cherri#53]
**Describe the bug**

When I set a variable to the result of an action, the resulting Shortcut includes a Set Variable action that sets the name of the variable to the value of the variable of the same name, which doesn't exist yet and doesn't work.

**To Reproduce**
The code to reproduce your issue if applicable:

```ruby
@test = getCurrentLocation()
```

**Debug output**

```
Parsing test.cherri...
Parsing includes...
### INCLUDES ###

## INCLUDED ##
[]

## INCLUDES MAP ##
[]

Done.

### PARSING ###

Previous Character:
) 2:0

Current Character:
EMPTY 2:0

Current Line:

## TOKENS ##
1 | {variable test action {getCurrentLocation []}}

## DEFINITIONS ##
Name: test
Color: -1263359489
Glyph: 61440
Inputs: []
Outputs: []
Workflows: []
No Input: { []}
macOS Only: false
Mininum Version: 2106.0.3
iOS Version: 17.0

## VARIABLES ##
@test = {getCurrentLocation []} (action)

## MENUS ##
map[]

## IMPORT QUESTIONS ##
map[]

Done.

Generating plist...### PLIST GEN ###

## UUIDS ##
map[test:a6b98d90-6a15-4ce3-8fcd-e700c8dfba16]

Done.

Writing to test.plist...Done.
Writing to test_unsigned.shortcut...Done.
```

**Expected behavior**

I expected the Set Variable action to reference the magic variable of the action performed.

**Screenshots**

![image](https://github.com/electrikmilk/cherri/assets/24325426/14bf07be-5a30-4b2d-b29f-243937158539)

**Version Information (please complete the following information):**
 - macOS version (run `uname -a`): `Linux cs-171148009998-default 6.1.77+ #1 SMP PREEMPT_DYNAMIC Sat May  4 16:42:09 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux` (I ran it on Linux, without signing/with `--skip-sign`)
 - Golang version (run `go version`): `go version go1.22.3 linux/amd64`

**Additional context**

This broke a couple days ago, and I think I know why!

This [commit to remove silly logic](https://github.com/electrikmilk/cherri/commit/48698cdf934ae1107e73882cc12a3b7130abf6e6) modified a conditional in the function `inputValue`. I would absolutely make this change, the conditional `!variable.repeatItem && (variable.constant && variable.valueType == Variable || variable.valueType != Variable)` looks redundant- but the operator precedence for `&&` is higher than `||`, and the conditional is better read as `!variable.repeatItem && ((variable.constant && variable.valueType == Variable) || variable.valueType != Variable)`.

Previously, the code would reference a magic variable if (the variable is not a repeat item AND EITHER (the variable is a constant and the variable's value type is a variable) OR (the variable's value type isn't a variable)). The commit makes it so that it references a magic variable if (the variable is not a repeat item AND the variable is a constant), which in turn makes it so actions being used in a mutable variable definition always reference their inputs as regular variables instead of magic variables.

I appreciate the work you're doing here. Cherri is easy to use and it helps me write Shortcuts without a lot of hassle. Thank you very much for your time and effort.

**Comment by electrikmilk** [comment]
Thank you so much for catching this! I now see the error of my ways, silly to remove this logic actually lol.
