### ISSUE TITLE
Cherri Playground errors while compiling Shortcuts that define their name right at the end

### ISSUE THREAD

**Issue by NoelTautges** [electrikmilk/cherri#57]
**Describe the bug**

When given a file that has a `#define name` statement right at the end, the [Cherri Playground](https://playground.cherrilang.org) will error when compiling.

**To Reproduce**

This doesn't work:

```ruby
#define name Test
```

This does:

```ruby
#define name Test

alert("Testing!")
```

**Expected behavior**

I expected the code to compile into a blank Shortcut with the name "Test". Instead, it errors with "Compiler Error", "Unable to compile Shortcut".

**Screenshots**

![image](https://github.com/electrikmilk/cherri/assets/24325426/8564d711-ffc5-4f24-a002-ae4b6a45147f)

**Additional context**

No such thing happens with the local compiler.

The POST call to `/compile` returns 200, but the subsequent call to the Shortcut itself returns 404.

Also, I was curious about the Playground itself- is it open source anywhere? And how often is the compiler on it updated?

**Comment by electrikmilk** [comment]
This should now be fixed, thank you for calling this out!

Currently, the source is not openly available due to security concerns. The compiler is updated with each release or as needed to fix a recently found bug.

**Comment by NoelTautges** [comment]
I'm reopening this (or rather, I would if I could) because now it's giving compiler errors if `#define name` is there unless it's the last statement. 😅

This doesn't work:

```ruby
#define name Test
alert("Testing!")
```

This does:

```ruby
#define name Test
```

**Comment by electrikmilk** [comment]
> I'm reopening this (or rather, I would if I could) because now it's giving compiler errors if `#define name` is there unless it's the last statement. 😅
> 
> This doesn't work:
> 
> ```ruby
> #define name Test
> alert("Testing!")
> ```
> 
> This does:
> 
> ```ruby
> #define name Test
> ```

Whoops, one last place I forgot to apply the fix. It looks to work now in both cases.
