### ISSUE TITLE
Hubsign invalid TLS certificate

### ISSUE THREAD

**Issue by electrikmilk** [electrikmilk/cherri#68]
**Describe the bug**

When macOS fails to sign the compiled Shortcut, we fall back on RoutineHub's signing service "HubSign".

Unfortunately, there appears to be an issue with the Hubsign service's TLS certificate.

```
panic: Post "https://hubsign.routinehub.services/sign": tls: failed to verify certificate: x509: certificate has expired or is not yet valid: “rout-shortcut.idap.pro” certificate is expired
```

**To Reproduce**

Attempt to sign a Shortcut using the Cherri compiler on macOS 14.4.1 or later or using the option `--hubsign`.

**Debug output**

```
Failed to sign Shortcut using macOS :(
Error: The data couldn’t be read because it isn’t in the correct format.

Signing using HubSign service...
Shortcut Signing Powered By RoutineHub

Program panic :(

panic: Post "https://hubsign.routinehub.services/sign": tls: failed to verify certificate: x509: certificate has expired or is not yet valid: “rout-shortcut.idap.pro” certificate is expired

goroutine 1 [running]:
main.panicDebug({0x105263680, 0x140000b0750})
        /Users/brandonjordan/cherri/main.go:190 +0x118
main.handle({0x105263680, 0x140000b0750})
        /Users/brandonjordan/cherri/main.go:92 +0x170
main.hubSign()
        /Users/brandonjordan/cherri/signing.go:96 +0x3ec
main.sign()
        /Users/brandonjordan/cherri/signing.go:61 +0x4f8
main.createShortcut()
        /Users/brandonjordan/cherri/output.go:43 +0x340
main.main()
        /Users/brandonjordan/cherri/main.go:80 +0x350
exit status 2
```

**Expected behavior**

A compiled Shortcut signed using Apple's AEA encryption to run on Apple devices.

**Version Information (please complete the following information):**
 - macOS version: Darwin Kernel Version 23.5.0: Wed May  1 20:16:51 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T8103
 - Golang version: go version go1.22.5 darwin/arm64

**Comment by electrikmilk** [comment]
This is still an issue for the compiler, but for playground.cherrilang.org, this issue is now fixed thanks to the folks over at RoutineHub!

**Comment by Xharry01X** [comment]
Routinehub sign service is free or any kind of subscription required?

**Comment by electrikmilk** [comment]
The certificate issue looks to have been fixed now.

**Comment by electrikmilk** [comment]
> Routinehub sign service is free or any kind of subscription required?

Yes, there is a subscription.
