### ISSUE TITLE
Simple menu causes compiler error

### ISSUE THREAD

**Issue by ifuchs** [electrikmilk/cherri#70]
Is there a forum somewhere to post sample scripts and compile problems or is this the right place?

In any case, what is wrong with this script? It produces a compile error with no indication of the cause. Probably the syntax, but I couldn't find any examples to use.

menu "Prompt" {
    item "Item 1":
        alert("howdy")
    item "Item 2":
        alert("do")
    }

**Comment by electrikmilk** [comment]
Hey, @ifuchs!

If you're experiencing any issues with Cherri, feel free to share them here. If there's anything else you'd like to discuss, I'm not currently aware of any other forums that have been set up. 

When you do share an issue, please use the provided template to make it easier for us to understand and address the problem.

- Are you using the latest version of the compiler?
- What error do you encounter when trying to compile this?
- Are you compiling locally or on the [playground site](https://playground.cherrilang.org)?

I've successfully compiled this on my machine:

![Screenshot 2024-09-18 at 10 01 34](https://github.com/user-attachments/assets/374fc30d-cf0f-4724-82cd-8a8f270435dc)

and also on the playground site:

![Screenshot 2024-09-18 at 10 01 11](https://github.com/user-attachments/assets/7e41cfb5-bf3b-427c-9094-490218b0550a)

If you can share more details about the issue I'll be able to look into it. Thank you for your interest in the project!
